packaging_format = 2

id = "plume"
name = "Plume"
description.en = "Federated blogging application"
description.fr = "Application de blogging fédérée"

version = "0.7.2~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-only"
website = "https://joinplu.me/"
demo = "https://joinplu.me/#instances"
admindoc = "https://docs.joinplu.me/"
code = "https://github.com/Plume-org/Plume"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.3.0"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "password"

    [install.name]
    ask.en = "Choose a name for your Plume instance"
    ask.fr = "Choisissez un nom pour votre instance Plume"
    type = "string"
    example = "My blog"
    default = "My blog"

    [install.registration]
    ask.en = "Is registrations open to everyone?"
    ask.fr = "Les inscriptions sont-elles ouvertes à tout le monde ?"
    type = "boolean"
    default = false

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/YunoHost-Apps/plume_ynh/releases/download/0.7.2/plume-arm64-postgres.tar.gz"
        arm64.sha256 = "921b3b209b2f3cb352c676ecb93730aa4732e239a53f59f1ec5f128d5b28ec42"
        amd64.url = "https://github.com/Plume-org/Plume/releases/download/0.7.2/plume-postgres.tar.gz"
        amd64.sha256 = "1a8c5a931fef25920503c9ae577b1c180ba7709e88f3d47b077ae80e2d9ea9ef"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.database]
    type = "postgresql"
